### ISSUE TITLE
Dasherize doesn’t work on CamelCase string

### ISSUE THREAD

**Issue by batisteo** [jpvanhal/inflection#28]
Expected
```python
>>> inflection.dasherize('ModelForm')
'model-form'
```
Getting:
```python
>>> inflection.dasherize('ModelForm')
'ModelForm'
```

**Comment by drozdvadym** [comment]
As from docs: 

> Replace underscores with dashes in the string.



https://inflection.readthedocs.io/en/latest/#inflection.dasherize

**Comment by jpvanhal** [comment]
Yes, that is expected behavior. Use `underscore` to first convert the string to snake case:

```py
>>> inflection.dasherize(inflection.underscore('ModelForm'))
'model-form'
```
