### ISSUE TITLE
Add builds for python 3.6 and 3.7 on conda-forge

### ISSUE THREAD

**Issue by tdpetrou** [jpvanhal/inflection#35]
I was attempting to use conda-forge to install quandl which has inflection as a dependency, but it looks like inflection has only been built up to python 3.5. Is it possible to add 3.6 and 3.7?

**Comment by jpvanhal** [comment]
Hi, I just released 0.4.0 in PyPI. I'm not familiar with how conda-forge works so I don't know if that will build inflection for Python 3.6 and 3.7. If it doesn't, you might want to ping the folks at [https://github.com/conda-forge/inflection-feedstock](conda-forge/inflection-feedstock). It seems that's the repo where conda-forge builds for inflection are handled.
