### ISSUE TITLE
PyPI Release

### ISSUE THREAD

**Issue by gregschmit** [jpvanhal/inflection#39]
I noticed that there hasn't been a release of this package on PyPI since 2015, and that it is a pre-release version number. Since this package is certainly used in production, it would be nice to get it to version 1.0 and make a new release on PyPI. Why hasn't there been a more recent release? Has the original maintainer abandoned the project?

**Comment by hojalot** [comment]
I noticed this fork https://github.com/jinzhu/inflection does have a 1.0, which is linked here:
https://release-monitoring.org/project/20876/

It would be nice to have just one source of numbered releases.

**Comment by gregschmit** [comment]
@hojalot What? That doesn't look like a fork of this repo; it's written in Go rather than Python. It also has **less** commits.

**Comment by hojalot** [comment]
@gregschmit ... Oops, wrong language.  My mistake!

**Comment by jpvanhal** [comment]
I just released v0.4.0, so I think we can close this :)
