### ISSUE TITLE
Add PEP484 type hints

### ISSUE THREAD

**Issue by wwuck** [jpvanhal/inflection#44]
Proposal to add [PEP484](https://www.python.org/dev/peps/pep-0484/) type hints and related [PEP561](https://www.python.org/dev/peps/pep-0561/) packaging information to inflection.  Since the lowest support python3 here appears to be 3.5, we can just use [typing](https://docs.python.org/3/library/typing.html) library directly without using type hint comments.

**Comment by wwuck** [comment]
Just realised that Pypy doesn't appear to support type hints :(

https://doc.pypy.org/en/latest/faq.html#would-type-annotations-help-pypy-s-performance

Would that be a blocker for this issue?

**Comment by jpvanhal** [comment]
Hi, thanks for the proposal and the PR! I've been thinking about adding type hints myself as well  :)
> Just realised that Pypy doesn't appear to support type hints :(
> 
> [doc.pypy.org/en/latest/faq.html#would-type-annotations-help-pypy-s-performance](https://doc.pypy.org/en/latest/faq.html#would-type-annotations-help-pypy-s-performance)
> 
> Would that be a blocker for this issue?

I was checking the Travis logs for your PR and it looks like the [Pypy build](https://travis-ci.org/github/jpvanhal/inflection/jobs/690792846) is failing to  install `typed-ast` package. See also https://github.com/python/typed_ast/issues/111.

`typed-ast` is a dependency of `mypy`. If installation of `mypy` and thus the static type checking was skipped on Pypy build, I'd assume that would make the whole build green. So I don't see this as a blocker.

**Comment by wwuck** [comment]
I've skipped mypy on pypy3 tox run, so it should all be fine now.

**Comment by jpvanhal** [comment]
Thanks, @wwuck! This is included in v0.5.0.

**Comment by henryiii** [comment]
It looks like you added type hints (fantastic), but forgot to add the `py.typed` file to your MANIFEST.in, so downstream projects can't use it. :'(

I'd highly recommend check-manifest to avoid this in the future. Maybe in a pre-commit check or something. [docs](https://scikit-hep.org/developer/style#check-manifest).
